<a href="https://colab.research.google.com/github/YounkoA/Python-Nootbook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy

In [7]:
x=6
x

6

In [8]:
a=x+2
a

8

In [9]:
b=x-5                
b

1

In [10]:
c=x*2                
c

12

In [11]:
d=x**2               
d

36

In [13]:
e=x%4                
e

2

In [14]:
f= x/float(2)
f

3.0

In [ ]:
#string operation

In [15]:
my_string = 'thisStringIsAwesome'
my_string

'thisStringIsAwesome'

In [16]:
my_string * 2
my_string

'thisStringIsAwesome'

In [17]:
my_string + 'Innit'
my_string

'thisStringIsAwesome'

In [18]:
'm' in my_string 

True

In [ ]:
#Lists

In [19]:
a = 'is'
b = 'nice'
my_list = ['my', 'list', a, b]
my_list2 = [[4,5,6,7], [3,4,5,6]]

In [20]:
#Subset
my_list[1]

'list'

In [21]:
g= my_list[-3]
g

'list'

In [22]:
#Slice
h=my_list[1:3]
h

['list', 'is']

In [23]:
i=my_list[1:]
i

['list', 'is', 'nice']

In [24]:
my_list[:3]
my_list

['my', 'list', 'is', 'nice']

In [25]:
j=my_list[:]
j

['my', 'list', 'is', 'nice']

In [26]:
#Subset Lists of Lists
k=my_list2[1][0]
k

3

In [27]:
l=my_list2[1][:2]
l

[3, 4]

In [28]:
#List Operations

In [29]:
m=my_list + my_list
m

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [30]:
n=my_list * 2
n

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
# >>> list methods
# my_list.index(a)   Get the index of an item          
# >>>
# my_list.count(a) Count an item
# >>>
# my_list.append('!') Append an item at a time
# >>>
# my_list.remove('!') Remove an item
# >>> del(my_list[0:1]) Remove an item
# >>> 
# my_list.reverse() Reverse the list

# >>> 
# my_list.extend('!') Append an item
# >>> my_list.pop(-1) Remove an item
# >>> my_list.insert(0,'!') Insert an item
# >>> my_list.sort() Sort the list

In [ ]:
#string methods
# >>> my_string.upper() String to uppercase
# >>> my_string.lower() String to lowercase
# >>> my_string.count('w') Count String elements
# >>> my_string.replace('e', 'i') Replace String elements
# >>> my_string.strip() Strip whitespaces

In [31]:
#Import libraries
import numpy as np
#Selective import
from math import pi

In [32]:
#numpy arrays
o=my_list = [1, 2, 3, 4]
o

[1, 2, 3, 4]

In [33]:
p= my_array = np.array(my_list)
p

array([1, 2, 3, 4])

In [34]:
q=my_2darray = np.array([[1,2,3],[4,5,6]])
q

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#selectring numpy array elements

In [35]:
#Subset
r=my_array[1]
r

2

In [36]:
#Slice
s=my_array[0:2]
s

array([1, 2])

In [37]:
#Subset 2D Numpy arrays
t=my_2darray[:,0]
t

array([1, 4])

In [ ]:
#numpy array operations

In [38]:
u= my_array > 3
u


array([False, False, False,  True])

In [39]:
v= my_array * 2
v


array([2, 4, 6, 8])

In [40]:
w= my_array + np.array([5, 6, 7, 8])
w

array([ 6,  8, 10, 12])

In [ ]:
#numpy array function

In [ ]:
# >>> my_array.shape Get the dimensions of the array
# >>> np.append(other_array) Append items to an array
# >>> np.insert(my_array, 1, 5) Insert items in an array
# >>> np.delete(my_array,[1]) Delete items in an array
# >>> np.mean(my_array) Mean of the array
# >>> np.median(my_array) Median of the array
# >>> my_array.corrcoef() Correlation coefficient
# >>> np.std(my_array) Standard deviation